/*
 * This source file was generated by the Gradle 'init' task
 */
package com.walsoft.rich_exception;

public class RichException extends  Exception {

    /**
     * RichBusinessException: Para violações de regras de negócio e fluxos de domínio (ex: saldo insuficiente, cupom expirado).
     *
     * RichDataException: Para falhas na camada de persistência, bancos de dados SQL/NoSQL e integridade de dados.
     *
     * RichIntegrationException: Para falhas em chamadas de APIs externas e serviços de terceiros (REST, SOAP, SDKs).
     *
     * RichCloudException: A "coringa" para infraestrutura de nuvem (IAM, Secrets, Quotas, Regions, Buckets). O detalhe técnico fica no Enum.
     *
     * RichIdentityException: Para tudo que envolve Autenticação, Autorização, Tokens (JWT) e Sessões de usuário.
     *
     * RichMessagingException: Para falhas em sistemas de mensageria e eventos (Kafka, RabbitMQ, SQS, Pub/Sub).
     *
     * RichValidationException: Para erros de entrada de dados, contratos de DTOs inválidos e falhas de parse de JSON/XML.
     *
     * RichInfrastructureException: Para recursos locais ou da JVM (falta de memória, variáveis de ambiente ausentes, falhas de I/O local).
     *
     * RichInternalException
     *
     * Math
     *
     * Report
     *
     * Parameter
     * Property
     * Json
     * Date
     * DateTime
     * Text
     * Auth
     * Api
     * @return
     */
}
